export const LEGEND_ITEMS = [
  { id: 'Wholesale and Retail Trade', name: 'Wholesale and Retail Trade', color: '#5B8FF9' },
  { id: 'Manufacturing', name: 'Manufacturing', color: '#CDDDFD' },
  { id: 'Leisure and hospitality', name: 'Leisure and hospitality', color: '#5AD8A6' },
  { id: 'Business services', name: 'Business services', color: '#CDF3E4' },
  { id: 'Construction', name: 'Construction', color: '#5D7092' },
  { id: 'Education and Health', name: 'Education and Health', color: '#CED4DE' },
  { id: 'Government', name: 'Government', color: '#F6BD16' },
  { id: 'Finance', name: 'Finance', color: '#FCEBB9' },
  { id: 'Self-employed', name: 'Self-employed', color: '#6F5EF9' },
  { id: 'Other', name: 'Other', color: '#D3CEFD' },
  { id: 'Transportation and Utilities', name: 'Transportation and Utilities', color: '#6DC8EC' },
  { id: 'Information', name: 'Information', color: '#D3EEF9' },
  { id: 'Agriculture', name: 'Agriculture', color: '#945FB9' },
  { id: 'Mining and Extraction', name: 'Mining and Extraction', color: '#DECFEA' },
];
